version: '3'
services:
  
  api:
    build:
      context: api
      dockerfile: Dockerfile
    image: explorer-api
    ports:
      - '5000:5000'
    

  client:
    build:
      context: client
      dockerfile: Dockerfile
    image: explorer-client
    ports:
      - '3000:80'
