version: '3'
services:
  
  api:
    env_file:
      - api/.env
    build:
      context: api
      dockerfile: Dockerfile
    image: explorer-api
    ports:
      - '5000:5000'
    

  client:
    build:
      context: client
      target: stage1
    image: explorer-client
    ports:
      - '3000:80'
